In [14]:
import pandas as pd

# Import results file to the same folder
df = pd.read_csv("results.csv")
print(f"#Entries: {len(df.columns)}")
df.columns

#Entries: 79

Index(['test', 'instance', 'passenger_count', 'id_instance', 'demand_size',
       'group_id', 'max_vehicle_capacity', 'fleet_size', 'total_capacity',
       'user_base', 'objective_function', 'run_time', 'total_delay_C_obj_val',
       'total_delay_B_obj_val', 'total_delay_A_obj_val',
       'first_tier_rides_C_obj_val', 'first_tier_rides_B_obj_val',
       'first_tier_rides_A_obj_val', 'fleet_capacity_obj_val',
       'total_delay_C_obj_mip_gap', 'total_delay_B_obj_mip_gap',
       'total_delay_A_obj_mip_gap', 'first_tier_rides_C_obj_mip_gap',
       'first_tier_rides_B_obj_mip_gap', 'first_tier_rides_A_obj_mip_gap',
       'fleet_capacity_obj_mip_gap', 'capacity_01', 'capacity_02',
       'capacity_03', 'capacity_04', 'pk_delay_mean_A', 'pk_delay_mean_B',
       'pk_delay_mean_C', 'pk_delay_sum_A', 'pk_delay_sum_B', 'pk_delay_sum_C',
       'ride_delay_mean_A', 'ride_delay_mean_B', 'ride_delay_mean_C',
       'ride_delay_sum_A', 'ride_delay_sum_B', 'ride_delay_sum_C', 'tier_1',
       'tier_1_A', 'tier_1_B', 'tier_1_C', 'tier_1_pk_delay_sum',
       'tier_1_pk_delay_sum_A', 'tier_1_pk_delay_sum_B',
       'tier_1_pk_delay_sum_C', 'tier_1_ride_delay_sum',
       'tier_1_ride_delay_sum_A', 'tier_1_ride_delay_sum_B',
       'tier_1_ride_delay_sum_C', 'tier_2', 'tier_2_A', 'tier_2_B', 'tier_2_C',
       'tier_2_pk_delay_sum', 'tier_2_pk_delay_sum_A', 'tier_2_pk_delay_sum_B',
       'tier_2_pk_delay_sum_C', 'tier_2_ride_delay_sum',
       'tier_2_ride_delay_sum_A', 'tier_2_ride_delay_sum_B',
       'tier_2_ride_delay_sum_C', 'total', 'total_A', 'total_B', 'total_C',
       'total_delay', 'total_pk_delay', 'total_pk_delay_A', 'total_pk_delay_B',
       'total_pk_delay_C', 'total_ride_delay', 'total_ride_delay_A',
       'total_ride_delay_B', 'total_ride_delay_C'],
      dtype='object')

In [15]:
columns = {
    "test":"Service quality",
    "id_instance": "Id",
    "demand_size":"#R",
    "user_base":"User base",
    "fleet_size": "#K",
    "pk_delay_mean_A": "Business(pk)",
    "pk_delay_mean_B": "Standard(pk)",
    "pk_delay_mean_C": "Low-cost(pk)",
    #"total_pk_delay_A": "Business(total)",
    #"total_pk_delay_B": "Standard(total)",
    #"total_pk_delay_C": "Low-cost(total)",
    "ride_delay_mean_A": "Business(ride)",
    "ride_delay_mean_B": "Standard(ride)",
    "ride_delay_mean_C": "Low-cost(ride)",
    #"total_A": "Business(total)",
    #"total_B": "Standard(total)",
    #"total_C": "Low-cost(total)",
    "total_pk_delay": "Pickup",
    "total_ride_delay": "Ride delay(s)",
    #"total_delay": "Total delay(s)",
    "run_time":"Runtime(s)"
}

sq_labels = dict(
    status_quo="Status quo",
    #slevels_050="50%",
    #slevels_080="80%",
    slevels_090="90%",
    slevels_100="100%"
)

u_base = dict(
    AA="B+",
    BB="S+",
    CC="L+",
    #B="B"
)
df = df[df["user_base"].isin(set(u_base.keys()))]
df = df[df["test"].isin(set(sq_labels.keys()))]

In [16]:
df["fleet_size"] = df["fleet_capacity_obj_val"]/df["max_vehicle_capacity"]

filter_cols = list(columns.keys())

dff = df[filter_cols]

dff

,test,id_instance,demand_size,user_base,fleet_size,pk_delay_mean_A,pk_delay_mean_B,pk_delay_mean_C,ride_delay_mean_A,ride_delay_mean_B,ride_delay_mean_C,total_pk_delay,total_ride_delay,run_time
2,slevels_090,1,10,AA,8.0,71.800000,29.000000,207.666667,0.0,0.000000,34.333333,1040.0,103.0,0.826866
3,slevels_100,1,10,AA,8.0,71.800000,29.000000,207.666667,0.0,0.000000,34.333333,1040.0,103.0,1.299826
4,status_quo,1,10,AA,8.0,71.800000,29.000000,218.000000,0.0,0.000000,24.000000,1071.0,72.0,1.162912
7,slevels_090,2,10,AA,8.0,71.400000,102.750000,273.000000,0.0,0.000000,0.000000,1041.0,0.0,0.076794
8,slevels_100,2,10,AA,8.0,71.400000,102.750000,273.000000,0.0,0.000000,0.000000,1041.0,0.0,0.066824
9,status_quo,2,10,AA,7.0,126.200000,102.750000,273.000000,0.0,0.000000,0.000000,1315.0,0.0,0.167553
12,slevels_090,3,10,AA,9.0,135.444444,NaN,117.000000,0.0,NaN,0.000000,1336.0,0.0,0.054243
13,slevels_100,3,10,AA,10.0,96.000000,NaN,117.000000,0.0,NaN,0.000000,981.0,0.0,0.024935
14,status_quo,3,10,AA,8.0,153.777778,NaN,117.000000,0.0,NaN,0.000000,1501.0,0.0,0.059841
17,slevels_090,4,10,AA,10.0,99.750000,209.000000,NaN,0.0,0.000000,NaN,1216.0,0.0,0.044882
18,slevels_100,4,10,AA,10.0,99.750000,209.000000,NaN,0.0,0.000000,NaN,1216.0,0.0,0.023935
19,status_quo,4,10,AA,9.0,144.750000,185.000000,NaN,0.0,0.000000,NaN,1528.0,0.0,0.072803
22,slevels_090,5,10,AA,8.0,87.000000,178.000000,197.000000,0.0,0.000000,0.000000,1382.0,0.0,0.051857
23,slevels_100,5,10,AA,8.0,87.000000,178.000000,197.000000,0.0,0.000000,0.000000,1382.0,0.0,0.058844
24,status_quo,5,10,AA,7.0,129.600000,178.000000,197.000000,0.0,0.000000,0.000000,1595.0,0.0,0.188519
27,slevels_090,1,10,BB,7.0,116.000000,164.875000,NaN,0.0,3.375000,NaN,1551.0,27.0,0.923534
28,slevels_100,1,10,BB,8.0,116.000000,115.250000,NaN,0.0,3.375000,NaN,1154.0,27.0,0.170544
29,status_quo,1,10,BB,6.0,235.000000,163.250000,NaN,0.0,3.375000,NaN,1776.0,27.0,1.269138
32,slevels_090,2,10,BB,5.0,NaN,174.666667,148.750000,NaN,36.333333,54.000000,1643.0,434.0,51.049639
33,slevels_100,2,10,BB,6.0,NaN,121.000000,148.750000,NaN,12.666667,18.500000,1321.0,150.0,13.661507
34,status_quo,2,10,BB,5.0,NaN,174.666667,148.750000,NaN,36.333333,54.000000,1643.0,434.0,61.826023
37,slevels_090,3,10,BB,7.0,50.000000,112.571429,173.000000,0.0,47.142857,29.000000,1184.0,388.0,1.420197
38,slevels_100,3,10,BB,7.0,50.000000,112.571429,173.000000,0.0,47.142857,29.000000,1184.0,388.0,0.592966
39,status_quo,3,10,BB,6.0,50.000000,151.142857,170.500000,0.0,58.428571,135.000000,1449.0,679.0,3.983677
42,slevels_090,4,10,BB,6.0,0.000000,90.625000,20.000000,0.0,33.750000,89.000000,745.0,359.0,11.150370
43,slevels_100,4,10,BB,6.0,0.000000,90.625000,20.000000,0.0,33.750000,89.000000,745.0,359.0,3.655710
44,status_quo,4,10,BB,6.0,0.000000,90.625000,20.000000,0.0,33.750000,89.000000,745.0,359.0,38.994617
47,slevels_090,5,10,BB,5.0,78.000000,179.500000,94.333333,0.0,48.166667,72.000000,1438.0,505.0,6.291849
48,slevels_100,5,10,BB,6.0,78.000000,120.666667,196.333333,0.0,34.000000,72.000000,1391.0,420.0,5.810310
49,status_quo,5,10,BB,5.0,78.000000,186.500000,91.666667,0.0,34.000000,72.000000,1472.0,420.0,5.031952
52,slevels_090,1,10,CC,7.0,119.000000,65.000000,242.600000,0.0,0.000000,0.000000,1700.0,0.0,0.423746
53,slevels_100,1,10,CC,7.0,119.000000,65.000000,242.600000,0.0,0.000000,0.000000,1700.0,0.0,0.380978
54,status_quo,1,10,CC,6.0,164.333333,65.000000,300.800000,0.0,0.000000,0.000000,2127.0,0.0,1.151230
57,slevels_090,2,10,CC,7.0,NaN,32.000000,156.000000,NaN,0.000000,66.777778,1436.0,601.0,0.116690
58,slevels_100,2,10,CC,7.0,NaN,32.000000,156.000000,NaN,0.000000,66.777778,1436.0,601.0,0.144127
59,status_quo,2,10,CC,7.0,NaN,32.000000,156.000000,NaN,0.000000,66.777778,1436.0,601.0,0.336098
62,slevels_090,3,10,CC,6.0,NaN,NaN,184.200000,NaN,NaN,42.100000,1842.0,421.0,5.406294
63,slevels_100,3,10,CC,6.0,NaN,NaN,184.200000,NaN,NaN,42.100000,1842.0,421.0,5.180197
64,status_quo,3,10,CC,6.0,NaN,NaN,184.200000,NaN,NaN,42.100000,1842.0,421.0,3.891903
67,slevels_090,4,10,CC,6.0,NaN,173.333333,113.000000,NaN,0.166667,0.250000,1492.0,2.0,98.254156
68,slevels_100,4,10,CC,7.0,NaN,117.666667,150.250000,NaN,0.166667,0.000000,1307.0,1.0,14.284992
69,status_quo,4,10,CC,6.0,NaN,173.000000,150.250000,NaN,0.166667,0.000000,1639.0,1.0,408.993544
72,slevels_090,5,10,CC,6.0,65.500000,236.000000,161.142857,0.0,0.000000,73.285714,1495.0,513.0,1.515579
73,slevels_100,5,10,CC,6.0,65.500000,236.000000,161.142857,0.0,0.000000,73.285714,1495.0,513.0,1.148474
74,status_quo,5,10,CC,6.0,65.500000,236.000000,161.142857,0.0,0.000000,73.285714,1495.0,513.0,1.256445

In [17]:
dff = dff.sort_values(by=['demand_size', 'user_base', 'test', 'id_instance', 'run_time'])

dff

,test,id_instance,demand_size,user_base,fleet_size,pk_delay_mean_A,pk_delay_mean_B,pk_delay_mean_C,ride_delay_mean_A,ride_delay_mean_B,ride_delay_mean_C,total_pk_delay,total_ride_delay,run_time
2,slevels_090,1,10,AA,8.0,71.800000,29.000000,207.666667,0.0,0.000000,34.333333,1040.0,103.0,0.826866
7,slevels_090,2,10,AA,8.0,71.400000,102.750000,273.000000,0.0,0.000000,0.000000,1041.0,0.0,0.076794
12,slevels_090,3,10,AA,9.0,135.444444,NaN,117.000000,0.0,NaN,0.000000,1336.0,0.0,0.054243
17,slevels_090,4,10,AA,10.0,99.750000,209.000000,NaN,0.0,0.000000,NaN,1216.0,0.0,0.044882
22,slevels_090,5,10,AA,8.0,87.000000,178.000000,197.000000,0.0,0.000000,0.000000,1382.0,0.0,0.051857
3,slevels_100,1,10,AA,8.0,71.800000,29.000000,207.666667,0.0,0.000000,34.333333,1040.0,103.0,1.299826
8,slevels_100,2,10,AA,8.0,71.400000,102.750000,273.000000,0.0,0.000000,0.000000,1041.0,0.0,0.066824
13,slevels_100,3,10,AA,10.0,96.000000,NaN,117.000000,0.0,NaN,0.000000,981.0,0.0,0.024935
18,slevels_100,4,10,AA,10.0,99.750000,209.000000,NaN,0.0,0.000000,NaN,1216.0,0.0,0.023935
23,slevels_100,5,10,AA,8.0,87.000000,178.000000,197.000000,0.0,0.000000,0.000000,1382.0,0.0,0.058844
4,status_quo,1,10,AA,8.0,71.800000,29.000000,218.000000,0.0,0.000000,24.000000,1071.0,72.0,1.162912
9,status_quo,2,10,AA,7.0,126.200000,102.750000,273.000000,0.0,0.000000,0.000000,1315.0,0.0,0.167553
14,status_quo,3,10,AA,8.0,153.777778,NaN,117.000000,0.0,NaN,0.000000,1501.0,0.0,0.059841
19,status_quo,4,10,AA,9.0,144.750000,185.000000,NaN,0.0,0.000000,NaN,1528.0,0.0,0.072803
24,status_quo,5,10,AA,7.0,129.600000,178.000000,197.000000,0.0,0.000000,0.000000,1595.0,0.0,0.188519
27,slevels_090,1,10,BB,7.0,116.000000,164.875000,NaN,0.0,3.375000,NaN,1551.0,27.0,0.923534
32,slevels_090,2,10,BB,5.0,NaN,174.666667,148.750000,NaN,36.333333,54.000000,1643.0,434.0,51.049639
37,slevels_090,3,10,BB,7.0,50.000000,112.571429,173.000000,0.0,47.142857,29.000000,1184.0,388.0,1.420197
42,slevels_090,4,10,BB,6.0,0.000000,90.625000,20.000000,0.0,33.750000,89.000000,745.0,359.0,11.150370
47,slevels_090,5,10,BB,5.0,78.000000,179.500000,94.333333,0.0,48.166667,72.000000,1438.0,505.0,6.291849
28,slevels_100,1,10,BB,8.0,116.000000,115.250000,NaN,0.0,3.375000,NaN,1154.0,27.0,0.170544
33,slevels_100,2,10,BB,6.0,NaN,121.000000,148.750000,NaN,12.666667,18.500000,1321.0,150.0,13.661507
38,slevels_100,3,10,BB,7.0,50.000000,112.571429,173.000000,0.0,47.142857,29.000000,1184.0,388.0,0.592966
43,slevels_100,4,10,BB,6.0,0.000000,90.625000,20.000000,0.0,33.750000,89.000000,745.0,359.0,3.655710
48,slevels_100,5,10,BB,6.0,78.000000,120.666667,196.333333,0.0,34.000000,72.000000,1391.0,420.0,5.810310
29,status_quo,1,10,BB,6.0,235.000000,163.250000,NaN,0.0,3.375000,NaN,1776.0,27.0,1.269138
34,status_quo,2,10,BB,5.0,NaN,174.666667,148.750000,NaN,36.333333,54.000000,1643.0,434.0,61.826023
39,status_quo,3,10,BB,6.0,50.000000,151.142857,170.500000,0.0,58.428571,135.000000,1449.0,679.0,3.983677
44,status_quo,4,10,BB,6.0,0.000000,90.625000,20.000000,0.0,33.750000,89.000000,745.0,359.0,38.994617
49,status_quo,5,10,BB,5.0,78.000000,186.500000,91.666667,0.0,34.000000,72.000000,1472.0,420.0,5.031952
52,slevels_090,1,10,CC,7.0,119.000000,65.000000,242.600000,0.0,0.000000,0.000000,1700.0,0.0,0.423746
57,slevels_090,2,10,CC,7.0,NaN,32.000000,156.000000,NaN,0.000000,66.777778,1436.0,601.0,0.116690
62,slevels_090,3,10,CC,6.0,NaN,NaN,184.200000,NaN,NaN,42.100000,1842.0,421.0,5.406294
67,slevels_090,4,10,CC,6.0,NaN,173.333333,113.000000,NaN,0.166667,0.250000,1492.0,2.0,98.254156
72,slevels_090,5,10,CC,6.0,65.500000,236.000000,161.142857,0.0,0.000000,73.285714,1495.0,513.0,1.515579
53,slevels_100,1,10,CC,7.0,119.000000,65.000000,242.600000,0.0,0.000000,0.000000,1700.0,0.0,0.380978
58,slevels_100,2,10,CC,7.0,NaN,32.000000,156.000000,NaN,0.000000,66.777778,1436.0,601.0,0.144127
63,slevels_100,3,10,CC,6.0,NaN,NaN,184.200000,NaN,NaN,42.100000,1842.0,421.0,5.180197
68,slevels_100,4,10,CC,7.0,NaN,117.666667,150.250000,NaN,0.166667,0.000000,1307.0,1.0,14.284992
73,slevels_100,5,10,CC,6.0,65.500000,236.000000,161.142857,0.0,0.000000,73.285714,1495.0,513.0,1.148474
54,status_quo,1,10,CC,6.0,164.333333,65.000000,300.800000,0.0,0.000000,0.000000,2127.0,0.0,1.151230
59,status_quo,2,10,CC,7.0,NaN,32.000000,156.000000,NaN,0.000000,66.777778,1436.0,601.0,0.336098
64,status_quo,3,10,CC,6.0,NaN,NaN,184.200000,NaN,NaN,42.100000,1842.0,421.0,3.891903
69,status_quo,4,10,CC,6.0,NaN,173.000000,150.250000,NaN,0.166667,0.000000,1639.0,1.0,408.993544
74,status_quo,5,10,CC,6.0,65.500000,236.000000,161.142857,0.0,0.000000,73.285714,1495.0,513.0,1.256445

In [18]:
dfff =dff.loc[dff["demand_size"]<=15]
dfff = dfff.rename(columns=columns)
dfff.head(50)

,Service quality,Id,#R,User base,#K,Business(pk),Standard(pk),Low-cost(pk),Business(ride),Standard(ride),Low-cost(ride),Pickup,Ride delay(s),Runtime(s)
2,slevels_090,1,10,AA,8.0,71.800000,29.000000,207.666667,0.0,0.000000,34.333333,1040.0,103.0,0.826866
7,slevels_090,2,10,AA,8.0,71.400000,102.750000,273.000000,0.0,0.000000,0.000000,1041.0,0.0,0.076794
12,slevels_090,3,10,AA,9.0,135.444444,NaN,117.000000,0.0,NaN,0.000000,1336.0,0.0,0.054243
17,slevels_090,4,10,AA,10.0,99.750000,209.000000,NaN,0.0,0.000000,NaN,1216.0,0.0,0.044882
22,slevels_090,5,10,AA,8.0,87.000000,178.000000,197.000000,0.0,0.000000,0.000000,1382.0,0.0,0.051857
3,slevels_100,1,10,AA,8.0,71.800000,29.000000,207.666667,0.0,0.000000,34.333333,1040.0,103.0,1.299826
8,slevels_100,2,10,AA,8.0,71.400000,102.750000,273.000000,0.0,0.000000,0.000000,1041.0,0.0,0.066824
13,slevels_100,3,10,AA,10.0,96.000000,NaN,117.000000,0.0,NaN,0.000000,981.0,0.0,0.024935
18,slevels_100,4,10,AA,10.0,99.750000,209.000000,NaN,0.0,0.000000,NaN,1216.0,0.0,0.023935
23,slevels_100,5,10,AA,8.0,87.000000,178.000000,197.000000,0.0,0.000000,0.000000,1382.0,0.0,0.058844
4,status_quo,1,10,AA,8.0,71.800000,29.000000,218.000000,0.0,0.000000,24.000000,1071.0,72.0,1.162912
9,status_quo,2,10,AA,7.0,126.200000,102.750000,273.000000,0.0,0.000000,0.000000,1315.0,0.0,0.167553
14,status_quo,3,10,AA,8.0,153.777778,NaN,117.000000,0.0,NaN,0.000000,1501.0,0.0,0.059841
19,status_quo,4,10,AA,9.0,144.750000,185.000000,NaN,0.0,0.000000,NaN,1528.0,0.0,0.072803
24,status_quo,5,10,AA,7.0,129.600000,178.000000,197.000000,0.0,0.000000,0.000000,1595.0,0.0,0.188519
27,slevels_090,1,10,BB,7.0,116.000000,164.875000,NaN,0.0,3.375000,NaN,1551.0,27.0,0.923534
32,slevels_090,2,10,BB,5.0,NaN,174.666667,148.750000,NaN,36.333333,54.000000,1643.0,434.0,51.049639
37,slevels_090,3,10,BB,7.0,50.000000,112.571429,173.000000,0.0,47.142857,29.000000,1184.0,388.0,1.420197
42,slevels_090,4,10,BB,6.0,0.000000,90.625000,20.000000,0.0,33.750000,89.000000,745.0,359.0,11.150370
47,slevels_090,5,10,BB,5.0,78.000000,179.500000,94.333333,0.0,48.166667,72.000000,1438.0,505.0,6.291849
28,slevels_100,1,10,BB,8.0,116.000000,115.250000,NaN,0.0,3.375000,NaN,1154.0,27.0,0.170544
33,slevels_100,2,10,BB,6.0,NaN,121.000000,148.750000,NaN,12.666667,18.500000,1321.0,150.0,13.661507
38,slevels_100,3,10,BB,7.0,50.000000,112.571429,173.000000,0.0,47.142857,29.000000,1184.0,388.0,0.592966
43,slevels_100,4,10,BB,6.0,0.000000,90.625000,20.000000,0.0,33.750000,89.000000,745.0,359.0,3.655710
48,slevels_100,5,10,BB,6.0,78.000000,120.666667,196.333333,0.0,34.000000,72.000000,1391.0,420.0,5.810310
29,status_quo,1,10,BB,6.0,235.000000,163.250000,NaN,0.0,3.375000,NaN,1776.0,27.0,1.269138
34,status_quo,2,10,BB,5.0,NaN,174.666667,148.750000,NaN,36.333333,54.000000,1643.0,434.0,61.826023
39,status_quo,3,10,BB,6.0,50.000000,151.142857,170.500000,0.0,58.428571,135.000000,1449.0,679.0,3.983677
44,status_quo,4,10,BB,6.0,0.000000,90.625000,20.000000,0.0,33.750000,89.000000,745.0,359.0,38.994617
49,status_quo,5,10,BB,5.0,78.000000,186.500000,91.666667,0.0,34.000000,72.000000,1472.0,420.0,5.031952
52,slevels_090,1,10,CC,7.0,119.000000,65.000000,242.600000,0.0,0.000000,0.000000,1700.0,0.0,0.423746
57,slevels_090,2,10,CC,7.0,NaN,32.000000,156.000000,NaN,0.000000,66.777778,1436.0,601.0,0.116690
62,slevels_090,3,10,CC,6.0,NaN,NaN,184.200000,NaN,NaN,42.100000,1842.0,421.0,5.406294
67,slevels_090,4,10,CC,6.0,NaN,173.333333,113.000000,NaN,0.166667,0.250000,1492.0,2.0,98.254156
72,slevels_090,5,10,CC,6.0,65.500000,236.000000,161.142857,0.0,0.000000,73.285714,1495.0,513.0,1.515579
53,slevels_100,1,10,CC,7.0,119.000000,65.000000,242.600000,0.0,0.000000,0.000000,1700.0,0.0,0.380978
58,slevels_100,2,10,CC,7.0,NaN,32.000000,156.000000,NaN,0.000000,66.777778,1436.0,601.0,0.144127
63,slevels_100,3,10,CC,6.0,NaN,NaN,184.200000,NaN,NaN,42.100000,1842.0,421.0,5.180197
68,slevels_100,4,10,CC,7.0,NaN,117.666667,150.250000,NaN,0.166667,0.000000,1307.0,1.0,14.284992
73,slevels_100,5,10,CC,6.0,65.500000,236.000000,161.142857,0.0,0.000000,73.285714,1495.0,513.0,1.148474
54,status_quo,1,10,CC,6.0,164.333333,65.000000,300.800000,0.0,0.000000,0.000000,2127.0,0.0,1.151230
59,status_quo,2,10,CC,7.0,NaN,32.000000,156.000000,NaN,0.000000,66.777778,1436.0,601.0,0.336098
64,status_quo,3,10,CC,6.0,NaN,NaN,184.200000,NaN,NaN,42.100000,1842.0,421.0,3.891903
69,status_quo,4,10,CC,6.0,NaN,173.000000,150.250000,NaN,0.166667,0.000000,1639.0,1.0,408.993544
74,status_quo,5,10,CC,6.0,65.500000,236.000000,161.142857,0.0,0.000000,73.285714,1495.0,513.0,1.256445

In [19]:
dfff = dfff.groupby(["#R", "User base", "Service quality"]).mean()
dfff = dfff.sort_values(by=["#R", "User base", "Service quality"])
dfff

                              Id   #K  Business(pk)  Standard(pk)  \
#R User base Service quality
10 AA        slevels_090       3  8.6     93.078889    129.687500
             slevels_100       3  8.8     85.190000    129.687500
             status_quo        3  7.8    125.225556    123.687500
   BB        slevels_090       3  6.0     61.000000    144.447619
             slevels_100       3  6.6     61.000000    112.022619
             status_quo        3  5.6     90.750000    153.236905
   CC        slevels_090       3  6.4     92.250000    126.583333
             slevels_100       3  6.6     92.250000    112.666667
             status_quo        3  6.2    114.916667    126.500000

                              Low-cost(pk)  Business(ride)  Standard(ride)  \
#R User base Service quality
10 AA        slevels_090        198.666667             0.0        0.000000
             slevels_100        198.666667             0.0        0.000000
             status_quo         201.250000             0.0        0.000000
   BB        slevels_090        109.020833             0.0       33.753571
             slevels_100        134.520833             0.0       26.186905
             status_quo         107.729167             0.0       33.177381
   CC        slevels_090        171.388571             0.0        0.041667
             slevels_100        178.838571             0.0        0.041667
             status_quo         190.478571             0.0        0.041667

                              Low-cost(ride)  Pickup  Ride delay(s)  \
#R User base Service quality
10 AA        slevels_090            8.583333  1203.0           20.6
             slevels_100            8.583333  1132.0           20.6
             status_quo             6.000000  1402.0           14.4
   BB        slevels_090           61.000000  1312.2          342.6
             slevels_100           52.125000  1159.0          268.8
             status_quo            87.500000  1417.0          383.8
   CC        slevels_090           36.482698  1593.0          307.4
             slevels_100           36.432698  1556.0          307.2
             status_quo            36.432698  1707.8          307.2

                              Runtime(s)
#R User base Service quality
10 AA        slevels_090        0.210928
             slevels_100        0.294873
             status_quo         0.330326
   BB        slevels_090       14.167118
             slevels_100        4.778207
             status_quo        22.221082
   CC        slevels_090       21.143293
             slevels_100        4.227753
             status_quo        83.125844

In [20]:
dfff = dfff.reset_index()

sqs = pd.api.types.CategoricalDtype(categories=list(sq_labels.values()), ordered=True)
ubases = pd.api.types.CategoricalDtype(categories=list(u_base.values()), ordered=True)

dfff["Service quality"] = dfff["Service quality"].apply(lambda x:sq_labels[x])
dfff["User base"] = dfff["User base"].apply(lambda x:u_base[x])

dfff["User base"] = dfff["User base"].astype(ubases)
dfff["Service quality"] = dfff["Service quality"].astype(sqs)

In [21]:
columns_to_remove = [
    "#R",
    "Id"
]

dfff = dfff.drop(columns_to_remove, axis=1)
dfff

,User base,Service quality,#K,Business(pk),Standard(pk),Low-cost(pk),Business(ride),Standard(ride),Low-cost(ride),Pickup,Ride delay(s),Runtime(s)
0,B+,90%,8.6,93.078889,129.687500,198.666667,0.0,0.000000,8.583333,1203.0,20.6,0.210928
1,B+,100%,8.8,85.190000,129.687500,198.666667,0.0,0.000000,8.583333,1132.0,20.6,0.294873
2,B+,Status quo,7.8,125.225556,123.687500,201.250000,0.0,0.000000,6.000000,1402.0,14.4,0.330326
3,S+,90%,6.0,61.000000,144.447619,109.020833,0.0,33.753571,61.000000,1312.2,342.6,14.167118
4,S+,100%,6.6,61.000000,112.022619,134.520833,0.0,26.186905,52.125000,1159.0,268.8,4.778207
5,S+,Status quo,5.6,90.750000,153.236905,107.729167,0.0,33.177381,87.500000,1417.0,383.8,22.221082
6,L+,90%,6.4,92.250000,126.583333,171.388571,0.0,0.041667,36.482698,1593.0,307.4,21.143293
7,L+,100%,6.6,92.250000,112.666667,178.838571,0.0,0.041667,36.432698,1556.0,307.2,4.227753
8,L+,Status quo,6.2,114.916667,126.500000,190.478571,0.0,0.041667,36.432698,1707.8,307.2,83.125844

In [22]:
# Blank cols to create latex
dfff["space_col_1"] = ""
dfff["space_col_2"] = ""
dfff["space_col_3"] = ""

df_added_blank_cols = dfff[
    [
        # "#R",
        "User base",
        "Service quality",
        "#K", "space_col_1",
        "Business(pk)",
        "Standard(pk)",
        "Low-cost(pk)",
        "space_col_2",
        "Business(ride)",
        "Standard(ride)",
        "Low-cost(ride)",
        "space_col_3",
        #"Pickup",
        #"Ride delay(s)",
        "Runtime(s)"
    ]
]
df_added_blank_cols

,User base,Service quality,#K,space_col_1,Business(pk),Standard(pk),Low-cost(pk),space_col_2,Business(ride),Standard(ride),Low-cost(ride),space_col_3,Runtime(s)
0,B+,90%,8.6,,93.078889,129.687500,198.666667,,0.0,0.000000,8.583333,,0.210928
1,B+,100%,8.8,,85.190000,129.687500,198.666667,,0.0,0.000000,8.583333,,0.294873
2,B+,Status quo,7.8,,125.225556,123.687500,201.250000,,0.0,0.000000,6.000000,,0.330326
3,S+,90%,6.0,,61.000000,144.447619,109.020833,,0.0,33.753571,61.000000,,14.167118
4,S+,100%,6.6,,61.000000,112.022619,134.520833,,0.0,26.186905,52.125000,,4.778207
5,S+,Status quo,5.6,,90.750000,153.236905,107.729167,,0.0,33.177381,87.500000,,22.221082
6,L+,90%,6.4,,92.250000,126.583333,171.388571,,0.0,0.041667,36.482698,,21.143293
7,L+,100%,6.6,,92.250000,112.666667,178.838571,,0.0,0.041667,36.432698,,4.227753
8,L+,Status quo,6.2,,114.916667,126.500000,190.478571,,0.0,0.041667,36.432698,,83.125844

In [23]:
def two(x):
    print(x, f"{x:.2f}")
    if x:
        return float(f"{x:.2f}")
    else:
        return "-"

# Only runtime is has two cases
df_added_blank_cols["Runtime(s)"]=df_added_blank_cols["Runtime(s)"].astype(str)
df_added_blank_cols = df_added_blank_cols.round(1)
df_added_blank_cols["Runtime(s)"] = df_added_blank_cols["Runtime(s)"].apply(lambda x:two(float(x)))

df_grouped = df_added_blank_cols.sort_values(by=
    [
        #"#R",
        "User base", "Service quality"])

df_grouped

0.2109283447265625 0.21
0.29487266540527346 0.29
0.33032569885253904 0.33
14.167117691040039 14.17
4.778207397460937 4.78
22.22108154296875 22.22
21.14329299926758 21.14
4.227753448486328 4.23
83.12584381103515 83.13

C:\Users\LocalAdmin\anaconda3\envs\env_slevels\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,User base,Service quality,#K,space_col_1,Business(pk),Standard(pk),Low-cost(pk),space_col_2,Business(ride),Standard(ride),Low-cost(ride),space_col_3,Runtime(s)
2,B+,Status quo,7.8,,125.2,123.7,201.2,,0.0,0.0,6.0,,0.33
0,B+,90%,8.6,,93.1,129.7,198.7,,0.0,0.0,8.6,,0.21
1,B+,100%,8.8,,85.2,129.7,198.7,,0.0,0.0,8.6,,0.29
5,S+,Status quo,5.6,,90.8,153.2,107.7,,0.0,33.2,87.5,,22.22
3,S+,90%,6.0,,61.0,144.4,109.0,,0.0,33.8,61.0,,14.17
4,S+,100%,6.6,,61.0,112.0,134.5,,0.0,26.2,52.1,,4.78
8,L+,Status quo,6.2,,114.9,126.5,190.5,,0.0,0.0,36.4,,83.13
6,L+,90%,6.4,,92.2,126.6,171.4,,0.0,0.0,36.5,,21.14
7,L+,100%,6.6,,92.2,112.7,178.8,,0.0,0.0,36.4,,4.23

In [24]:
df = df_grouped.set_index([
    # "#R",
    "User base", "Service quality"])
df

                            #K space_col_1  Business(pk)  Standard(pk)  \
User base Service quality
B+        Status quo       7.8                     125.2         123.7
          90%              8.6                      93.1         129.7
          100%             8.8                      85.2         129.7
S+        Status quo       5.6                      90.8         153.2
          90%              6.0                      61.0         144.4
          100%             6.6                      61.0         112.0
L+        Status quo       6.2                     114.9         126.5
          90%              6.4                      92.2         126.6
          100%             6.6                      92.2         112.7

                           Low-cost(pk) space_col_2  Business(ride)  \
User base Service quality
B+        Status quo              201.2                         0.0
          90%                     198.7                         0.0
          100%                    198.7                         0.0
S+        Status quo              107.7                         0.0
          90%                     109.0                         0.0
          100%                    134.5                         0.0
L+        Status quo              190.5                         0.0
          90%                     171.4                         0.0
          100%                    178.8                         0.0

                           Standard(ride)  Low-cost(ride) space_col_3  \
User base Service quality
B+        Status quo                  0.0             6.0
          90%                         0.0             8.6
          100%                        0.0             8.6
S+        Status quo                 33.2            87.5
          90%                        33.8            61.0
          100%                       26.2            52.1
L+        Status quo                  0.0            36.4
          90%                         0.0            36.5
          100%                        0.0            36.4

                           Runtime(s)
User base Service quality
B+        Status quo             0.33
          90%                    0.21
          100%                   0.29
S+        Status quo            22.22
          90%                   14.17
          100%                   4.78
L+        Status quo            83.13
          90%                   21.14
          100%                   4.23

In [25]:
df = df.astype(str)
df.to_csv("aggregated_results.csv")
df

                            #K space_col_1 Business(pk) Standard(pk)  \
User base Service quality
B+        Status quo       7.8                    125.2        123.7
          90%              8.6                     93.1        129.7
          100%             8.8                     85.2        129.7
S+        Status quo       5.6                     90.8        153.2
          90%              6.0                     61.0        144.4
          100%             6.6                     61.0        112.0
L+        Status quo       6.2                    114.9        126.5
          90%              6.4                     92.2        126.6
          100%             6.6                     92.2        112.7

                          Low-cost(pk) space_col_2 Business(ride)  \
User base Service quality
B+        Status quo             201.2                        0.0
          90%                    198.7                        0.0
          100%                   198.7                        0.0
S+        Status quo             107.7                        0.0
          90%                    109.0                        0.0
          100%                   134.5                        0.0
L+        Status quo             190.5                        0.0
          90%                    171.4                        0.0
          100%                   178.8                        0.0

                          Standard(ride) Low-cost(ride) space_col_3 Runtime(s)
User base Service quality
B+        Status quo                 0.0            6.0                   0.33
          90%                        0.0            8.6                   0.21
          100%                       0.0            8.6                   0.29
S+        Status quo                33.2           87.5                  22.22
          90%                       33.8           61.0                  14.17
          100%                      26.2           52.1                   4.78
L+        Status quo                 0.0           36.4                  83.13
          90%                        0.0           36.5                  21.14
          100%                       0.0           36.4                   4.23

In [26]:
print(df.astype(str).to_latex())

\begin{tabular}{lllllllllllll}
\toprule
   &      &   \#K & space\_col\_1 & Business(pk) & Standard(pk) & Low-cost(pk) & space\_col\_2 & Business(ride) & Standard(ride) & Low-cost(ride) & space\_col\_3 & Runtime(s) \\
User base & Service quality &      &             &              &              &              &             &                &                &                &             &            \\
\midrule
B+ & Status quo &  7.8 &             &        125.2 &        123.7 &        201.2 &             &            0.0 &            0.0 &            6.0 &             &       0.33 \\
   & 90\% &  8.6 &             &         93.1 &        129.7 &        198.7 &             &            0.0 &            0.0 &            8.6 &             &       0.21 \\
   & 100\% &  8.8 &             &         85.2 &        129.7 &        198.7 &             &            0.0 &            0.0 &            8.6 &             &       0.29 \\
S+ & Status quo &  5.6 &             &         90.8 &        153.2 &        107.7 &             &            0.0 &           33.2 &           87.5 &             &      22.22 \\
   & 90\% &  6.0 &             &         61.0 &        144.4 &        109.0 &             &            0.0 &           33.8 &           61.0 &             &      14.17 \\
   & 100\% &  6.6 &             &         61.0 &        112.0 &        134.5 &             &            0.0 &           26.2 &           52.1 &             &       4.78 \\
L+ & Status quo &  6.2 &             &        114.9 &        126.5 &        190.5 &             &            0.0 &            0.0 &           36.4 &             &      83.13 \\
   & 90\% &  6.4 &             &         92.2 &        126.6 &        171.4 &             &            0.0 &            0.0 &           36.5 &             &      21.14 \\
   & 100\% &  6.6 &             &         92.2 &        112.7 &        178.8 &             &            0.0 &            0.0 &           36.4 &             &       4.23 \\
\bottomrule
\end{tabular}